### ISSUE TITLE
Unit Test Files

### ISSUE THREAD

**Issue by lilleswing** [wenhao-gao/SynNet#1]
First off great work!

The unit tests reference files that are ignored in .gitignore
```
'./data/states_0_train.npz'
'./data/st_hb_test.json.gz'
'./data/building_blocks_matched.csv.gz'
```

can we add these to the repo so the unit tests can be run?

**Comment by rociomer** [comment]
Thanks, Karl!

We have added the building blocks file (forgot to push), and we updated the data prep tests so that they now run with the files available in `./tests/data/`.

We are still adding a few more unit tests (the placeholders for these will raise NotImplementedError-s), but the ones that are already implemented should pass.
