### ISSUE TITLE
Errors in creating env and running unit tests.

### ISSUE THREAD

**Issue by geemi725** [wenhao-gao/SynNet#3]
Hi,

I'd like to use SynNet in my work. I have followed the instructions in the README to setup my environment.

1.  In the `environment.yml `file the name is rdkit not synthenv. As a result, `source activate synthevn` as instructed in the readme does not work. You may want to take a look at these.

2.   When I ran the unit tests, it gives me a few errors. I think it's originating from the incorrect path specifications. One of the errors I have got: `FileNotFoundError: [Errno 2] No such file or directory: '/pool001/whgao/data/synth_net/st_hb/enamine_us_emb_gin.npy'` I noticed that there are multiple pathways as such, which might make it difficult to use in future computations without having to change each and everyone of them. 

Will you be able to help me with these? Thanks!

**Comment by yash4242** [comment]
Hello, I too have the error `FileNotFoundError: [Errno 2] No such file or directory: '/pool001/whgao/data/synth_net/st_hb/enamine_us_emb_gin.npy'` and so the unit tests fail. Requesting help with the missing files. Thanks!

**Comment by chrulm** [comment]
Hey, 

Thanks for the comments. 

1. I believe this was fixed in b46172e.
2. There are indeed many hard-coded paths. As of now, you would have to download the enamine building blocks yourself and then re-create the data, and finally change the paths. There's a WIP for an extended README here https://github.com/chrulm/SynNet/blob/refactor-syntree-generation/INSTRUCTIONS.md

**Comment by rociomer** [comment]
Hi Geemi,

We have addressed this and other issues in the new version of SynNet (thanks to @chrulm!). Closing this for now.
